### ISSUE TITLE
What is the file directory structure of the dataset?

### ISSUE THREAD

**Issue by qzcmask** [nickgkan/orange#1]
What is the file directory structure of the dataset?

like this?

```
- datasets
  - cornell
     -xxx1.txt
     -xxx1.png
     -xxx2.txt
     -xxx2.png
  -jaccard
```

**But errors can occur:**
```
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Hope to get your reply. Thank you!

**Comment by nickgkan** [comment]
Hi, thank you for your interest in our code.

Download Cornell from [here](http://pr.cs.cornell.edu/grasping/rect_data/data.php) and untar each folder.

The expected structure is:
```
- cornell
  - 01
    - *.txt
    - *.png
  - 02
  etc.
```

Then, run
```
python prepare_data.py cornell
```
to create the annotations.

If you have stored the dataset at a different path, e.g. datasets/, change line 21 at config.py to your path.

For jacquard, download and unzip everything, you don't have to change the directory structure as well.

**Comment by qzcmask** [comment]
Thank you, I will give a try.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nikolaos Gkanatsios"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月30日(星期二) 下午3:13
收件人:&nbsp;"nickgkan/orange"<orange@noreply.github.com&gt;;
抄送:&nbsp;"戚宗城"<923746590@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nickgkan/orange] What is the file directory structure of the dataset? (#1)





 
Hi, thank you for your interest in our code.
 
Download Cornell from here and untar each folder.
 
The expected structure is:
 - cornell   - 01     - *.txt     - *.png   - 02   etc.  
Then, run
 python prepare_data.py cornell  
to create the annotations.
 
If you have stored the dataset at a different path, e.g. datasets/, change line 21 at config.py to your path.
 
For jacquard, download and unzip everything, you don't have to change the directory structure as well.

**Comment by qzcmask** [comment]
Firstly, I can run `python prepare_data.py cornell`.



But after I running `python main.py`, it still occurred an error.&nbsp;


Please give me some help. Thank you!







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"戚宗城"<923746590@qq.com&gt;;
发送时间:&nbsp;2020年6月30日(星期二) 下午3:14
收件人:&nbsp;"nickgkan/orange"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [nickgkan/orange] What is the file directory structure of the dataset? (#1)



Thank you, I will give a try.




------------------ 原始邮件 ------------------
发件人:&nbsp;"Nikolaos Gkanatsios"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月30日(星期二) 下午3:13
收件人:&nbsp;"nickgkan/orange"<orange@noreply.github.com&gt;;
抄送:&nbsp;"戚宗城"<923746590@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nickgkan/orange] What is the file directory structure of the dataset? (#1)





 
Hi, thank you for your interest in our code.
 
Download Cornell from here and untar each folder.
 
The expected structure is:
 - cornell   - 01     - *.txt     - *.png   - 02   etc.  
Then, run
 python prepare_data.py cornell  
to create the annotations.
 
If you have stored the dataset at a different path, e.g. datasets/, change line 21 at config.py to your path.
 
For jacquard, download and unzip everything, you don't have to change the directory structure as well.

**Comment by nickgkan** [comment]
Did you specify the dataset to be cornell?

```
python main.py --dataset=cornell
```
See the README for an example in jacquard and, for your case, use ```cornell``` instead of ```jacquard```.

**Comment by qzcmask** [comment]
Yes, I had entered the dataset parameter.


The whole command I ran is `python main.py --dataset=cornell --model=unet --use_bin_loss --use_bin_attention_loss --use_graspness_loss`.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nikolaos Gkanatsios"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月30日(星期二) 下午3:49
收件人:&nbsp;"nickgkan/orange"<orange@noreply.github.com&gt;;
抄送:&nbsp;"戚宗城"<923746590@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nickgkan/orange] What is the file directory structure of the dataset? (#1)





 
Did you specify the dataset to be cornell?
 python main.py --dataset=cornell  
See the README for an example in jacquard and, for your case, use cornell instead of jacquard.

**Comment by qzcmask** [comment]
I suspect that the version of the components within the file `requirement.txt` are not specificed.


like this:
```
numpy
torch
torchvision
opencv-python
colorlog
matplotlib
Pillow
imageio
skimage
tqdm


```


Can you send me the version when you ran the&nbsp;experiment？


Thank you.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nikolaos Gkanatsios"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月30日(星期二) 下午3:49
收件人:&nbsp;"nickgkan/orange"<orange@noreply.github.com&gt;;
抄送:&nbsp;"戚宗城"<923746590@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nickgkan/orange] What is the file directory structure of the dataset? (#1)





 
Did you specify the dataset to be cornell?
 python main.py --dataset=cornell  
See the README for an example in jacquard and, for your case, use cornell instead of jacquard.

**Comment by nickgkan** [comment]
Well, can you paste the full error trace here?

**Comment by qzcmask** [comment]
ok, the full error is listed.


```
+(qzc_py36) autossh@wislab-2:~/qzc/codes/orange $ python main.py --dataset=cornell --model=unet --use_bin_loss --use_bin_attention_loss --use_graspness_loss


2020-06-30 15:25:41,455 - INFO - Performing training for unet_cornell
Traceback (most recent call last):
&nbsp; File "main.py", line 167, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "main.py", line 163, in main
&nbsp; &nbsp; model.train_test(cfg, model_params)
&nbsp; File "/media/wislab/Datasets_SSD/qzc/codes/orange/src/models/unet.py", line 120, in train_test
&nbsp; &nbsp; train_tester.train_test()
&nbsp; File "/media/wislab/Datasets_SSD/qzc/codes/orange/src/train_testers/base_train_tester.py", line 75, in train_test
&nbsp; &nbsp; epochs=50 if self._use_early_stopping else 10)
&nbsp; File "/media/wislab/Datasets_SSD/qzc/codes/orange/src/train_testers/base_train_tester.py", line 98, in train
&nbsp; &nbsp; self._set_data_loaders({'train': 0, 'val': 1})
&nbsp; File "/media/wislab/Datasets_SSD/qzc/codes/orange/src/train_testers/grasp_train_tester.py", line 147, in _set_data_loaders
&nbsp; &nbsp; annotations = json.load(fid)
&nbsp; File "/home/wislab/anaconda2/envs/qzc_py36/lib/python3.6/json/__init__.py", line 299, in load
&nbsp; &nbsp; parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
&nbsp; File "/home/wislab/anaconda2/envs/qzc_py36/lib/python3.6/json/__init__.py", line 354, in loads
&nbsp; &nbsp; return _default_decoder.decode(s)
&nbsp; File "/home/wislab/anaconda2/envs/qzc_py36/lib/python3.6/json/decoder.py", line 339, in decode
&nbsp; &nbsp; obj, end = self.raw_decode(s, idx=_w(s, 0).end())
&nbsp; File "/home/wislab/anaconda2/envs/qzc_py36/lib/python3.6/json/decoder.py", line 357, in raw_decode
&nbsp; &nbsp; raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nikolaos Gkanatsios"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月30日(星期二) 下午4:10
收件人:&nbsp;"nickgkan/orange"<orange@noreply.github.com&gt;;
抄送:&nbsp;"戚宗城"<923746590@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nickgkan/orange] What is the file directory structure of the dataset? (#1)





 
Well, can you paste the full error trace here?

**Comment by nickgkan** [comment]
It seems like the problem is in the json parsing. I will try to reproduce it but I'll need some time due to other deadlines pending,

**Comment by qzcmask** [comment]
ok, I am looking forward to hearing from you. Wish your other works success.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nikolaos Gkanatsios"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月1日(星期三) 凌晨5:16
收件人:&nbsp;"nickgkan/orange"<orange@noreply.github.com&gt;;
抄送:&nbsp;"戚宗城"<923746590@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nickgkan/orange] What is the file directory structure of the dataset? (#1)





 
It seems like the problem is in the json parsing. I will try to reproduce it but I'll need some time due to other deadlines pending,

**Comment by nickgkan** [comment]
Hi @qzcmask and thank you for your patience. I reproduced the error and it seems ok now. I also included a shell script to easily download Cornell. Can you please check if everything is ok now?

**Comment by qzcmask** [comment]
Thank you. It seems that everything is ok.


I have a question about the Cornell and Jacquard Dataset.&nbsp;Where can I get the object class from the dataset, such as the first picture is pen, the second picture is Eraser? Do you have any annotations? I can't find it in the internet.


Best wishes.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nickgkan/orange"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月11日(星期六) 中午1:46
收件人:&nbsp;"nickgkan/orange"<orange@noreply.github.com&gt;;
抄送:&nbsp;"戚宗城"<923746590@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [nickgkan/orange] What is the file directory structure of the dataset? (#1)





 
Hi @qzcmask an thank you for your patience. I reproduced the error and it seems ok now. I also included a shell script to easily download Cornell. Can you please check if everything is ok now?

**Comment by nickgkan** [comment]
Not really sure, but I think they are not public. However, for Jacquard, the objects are taken from ShapeNet, as stated here https://jacquard.liris.cnrs.fr/database.php so you can check that dataset to obtain the classes you want.


    Στις Σάββατο, 11 Ιουλίου 2020, 9:44:13 π.μ. EEST, ο χρήστης qzcmask <notifications@github.com> έγραψε:  
 
 

Thank you. It seems that everything is ok.


I have a question about the Cornell and Jacquard Dataset.&nbsp;Where can I get the object class from the dataset, such as the first picture is pen, the second picture is Eraser? Do you have any annotations? I can't find it in the internet.


Best wishes.


------------------&nbsp;原始邮件&nbsp;------------------
发件人: "nickgkan/orange" <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月11日(星期六) 中午1:46
收件人:&nbsp;"nickgkan/orange"<orange@noreply.github.com&gt;;
抄送:&nbsp;"戚宗城"<923746590@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [nickgkan/orange] What is the file directory structure of the dataset? (#1)





 
Hi @qzcmask an thank you for your patience. I reproduced the error and it seems ok now. I also included a shell script to easily download Cornell. Can you please check if everything is ok now?

**Comment by qzcmask** [comment]
ok, If I can't obtain the object class, how can I split the dataset into object-wise split?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nickgkan/orange"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月11日(星期六) 下午2:56
收件人:&nbsp;"nickgkan/orange"<orange@noreply.github.com&gt;;
抄送:&nbsp;"戚宗城"<923746590@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [nickgkan/orange] What is the file directory structure of the dataset? (#1)





  Not really sure, but I think they are not public. However, for Jacquard, the objects are taken from ShapeNet, as stated here&nbsp;https://jacquard.liris.cnrs.fr/database.php&nbsp;so you can check that dataset to obtain the classes you want.
 
 
     Στις Σάββατο, 11 Ιουλίου 2020, 9:44:13 π.μ. EEST, ο χρήστης qzcmask <notifications@github.com&gt; έγραψε:  
  
  
 
 Thank you. It seems that everything is ok.
 
 
 I have a question about the Cornell and Jacquard Dataset.&amp;nbsp;Where can I get the object class from the dataset, such as the first picture is pen, the second picture is Eraser? Do you have any annotations? I can't find it in the internet.
 
 
 Best wishes.
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "nickgkan/orange" <notifications@github.com&amp;gt;;
 发送时间:&amp;nbsp;2020年7月11日(星期六) 中午1:46
 收件人:&amp;nbsp;"nickgkan/orange"<orange@noreply.github.com&amp;gt;;
 抄送:&amp;nbsp;"戚宗城"<923746590@qq.com&amp;gt;;"Mention"<mention@noreply.github.com&amp;gt;;
 主题:&amp;nbsp;Re: [nickgkan/orange] What is the file directory structure of the dataset? (#1)
 
 
 
 
 
  
 Hi @qzcmask an thank you for your patience. I reproduced the error and it seems ok now. I also included a shell script to easily download Cornell. Can you please check if everything is ok now?

**Comment by nickgkan** [comment]
No need to do that to be comparable to other works, GGCNN does not do this either. If you want to do it for any reason, check ShapeNet. For Cornell, you can contact authors of other papers that claim to have done so.
    Στις Σάββατο, 11 Ιουλίου 2020, 10:00:22 π.μ. EEST, ο χρήστης qzcmask <notifications@github.com> έγραψε:  
 
 

ok, If I can't obtain the object class, how can I split the dataset into object-wise split?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "nickgkan/orange" <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月11日(星期六) 下午2:56
收件人:&nbsp;"nickgkan/orange"<orange@noreply.github.com&gt;;
抄送:&nbsp;"戚宗城"<923746590@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [nickgkan/orange] What is the file directory structure of the dataset? (#1)





 Not really sure, but I think they are not public. However, for Jacquard, the objects are taken from ShapeNet, as stated here&nbsp;https://jacquard.liris.cnrs.fr/database.php&nbsp;so you can check that dataset to obtain the classes you want.
 
 
 Στις Σάββατο, 11 Ιουλίου 2020, 9:44:13 π.μ. EEST, ο χρήστης qzcmask <notifications@github.com&gt; έγραψε: 
 
 
 
 Thank you. It seems that everything is ok.
 
 
 I have a question about the Cornell and Jacquard Dataset.&amp;nbsp;Where can I get the object class from the dataset, such as the first picture is pen, the second picture is Eraser? Do you have any annotations? I can't find it in the internet.
 
 
 Best wishes.
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "nickgkan/orange" <notifications@github.com&amp;gt;;
 发送时间:&amp;nbsp;2020年7月11日(星期六) 中午1:46
 收件人:&amp;nbsp;"nickgkan/orange"<orange@noreply.github.com&amp;gt;;
 抄送:&amp;nbsp;"戚宗城"<923746590@qq.com&amp;gt;;"Mention"<mention@noreply.github.com&amp;gt;;
 主题:&amp;nbsp;Re: [nickgkan/orange] What is the file directory structure of the dataset? (#1)
 
 
 
 
 
 
 Hi @qzcmask an thank you for your patience. I reproduced the error and it seems ok now. I also included a shell script to easily download Cornell. Can you please check if everything is ok now?

**Comment by qzcmask** [comment]
ok, thank you for your response.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nickgkan/orange"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月11日(星期六) 下午3:09
收件人:&nbsp;"nickgkan/orange"<orange@noreply.github.com&gt;;
抄送:&nbsp;"戚宗城"<923746590@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [nickgkan/orange] What is the file directory structure of the dataset? (#1)





  No need to do that to be comparable to other works, GGCNN does not do this either. If you want to do it for any reason, check ShapeNet. For Cornell, you can contact authors of other papers that claim to have done so.
     Στις Σάββατο, 11 Ιουλίου 2020, 10:00:22 π.μ. EEST, ο χρήστης qzcmask <notifications@github.com&gt; έγραψε:  
  
  
 
 ok, If I can't obtain the object class, how can I split the dataset into object-wise split?
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "nickgkan/orange" <notifications@github.com&amp;gt;;
 发送时间:&amp;nbsp;2020年7月11日(星期六) 下午2:56
 收件人:&amp;nbsp;"nickgkan/orange"<orange@noreply.github.com&amp;gt;;
 抄送:&amp;nbsp;"戚宗城"<923746590@qq.com&amp;gt;;"Mention"<mention@noreply.github.com&amp;gt;;
 主题:&amp;nbsp;Re: [nickgkan/orange] What is the file directory structure of the dataset? (#1)
 
 
 
 
 
  Not really sure, but I think they are not public. However, for Jacquard, the objects are taken from ShapeNet, as stated here&amp;nbsp;https://jacquard.liris.cnrs.fr/database.php&amp;nbsp;so you can check that dataset to obtain the classes you want.
  
  
  Στις Σάββατο, 11 Ιουλίου 2020, 9:44:13 π.μ. EEST, ο χρήστης qzcmask <notifications@github.com&amp;gt; έγραψε: 
  
  
  
  Thank you. It seems that everything is ok.
  
  
  I have a question about the Cornell and Jacquard Dataset.&amp;amp;nbsp;Where can I get the object class from the dataset, such as the first picture is pen, the second picture is Eraser? Do you have any annotations? I can't find it in the internet.
  
  
  Best wishes.
  
  
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------
  发件人: "nickgkan/orange" <notifications@github.com&amp;amp;gt;;
  发送时间:&amp;amp;nbsp;2020年7月11日(星期六) 中午1:46
  收件人:&amp;amp;nbsp;"nickgkan/orange"<orange@noreply.github.com&amp;amp;gt;;
  抄送:&amp;amp;nbsp;"戚宗城"<923746590@qq.com&amp;amp;gt;;"Mention"<mention@noreply.github.com&amp;amp;gt;;
  主题:&amp;amp;nbsp;Re: [nickgkan/orange] What is the file directory structure of the dataset? (#1)
  
  
  
  
  
  
  Hi @qzcmask an thank you for your patience. I reproduced the error and it seems ok now. I also included a shell script to easily download Cornell. Can you please check if everything is ok now?
