### ISSUE TITLE
I have some questions about the path of the datasets

### ISSUE THREAD

**Issue by thk8181** [nickgkan/orange#2]
If my datasets path is "/media/thk/datasets/jacquard/Jacquard_Dataset_0/"，Where do I need to change in config.py? I try many times, there were "json. The decoder. JSONDecodeError: Expecting value: line 1 column 1 0 (char)" such a mistake.

Thank you very much for your reply. Best wishes

**Comment by nickgkan** [comment]
Hi,

In config.py you should change DATA_FOLDER = "/media/thk/datasets/". This should work.

Thanks for your interest in our code.

**Comment by thk8181** [comment]
Thank you very much for your patient and careful reply.There are still two problems, I would like to consult you.

1.At present, the Cornell data set has been ok, but the jacquard is still not ok, after running "python prepare_data. Py jacquard", still shows "json. The decoder. JSONDecodeError: Expecting Value: Line 1 column 1 (char 0)".

2.When I run "python main.py --dataset= Cornell", I get "RuntimeError: Cuda Error: No kernel image is available for execution on the device ", but I have checked that both the PyTorch and CUDA versions are valid and can run other programs.

Looking forward to your reply and best wishes.

**Comment by nickgkan** [comment]
Hi again,

1. It seems that GitHub decided my fix for this is not a verified commit. Please pull and check now again.

2. I have never encountered this error, it seems that something is not compiled, but you don't need to compile anything for this repository. If you can find which line causes the problem it will be helpful.

**Comment by thk8181** [comment]
Thank you very much for your patient reply again. I am trying to solve the problem I met. Wish you all the best in your work.
