### ISSUE TITLE
Question about the prepare_data.py

### ISSUE THREAD

**Issue by mariiak2021** [nickgkan/orange#3]
Hello!

I'm experiencing troubles with the preparation of data for both jacquard and cornell datasets.
Inside config.py I have:
if os.path.exists('/data/'):
     DATA_FOLDER = '/data/'
as both datasets are inside data folder in the main repository:(/dstore/home/mkhan/orange/data/jacquard/Jacquard_Dataset_11/ffffcecd8fad215035836c728d324152)

The orig_data_path inside transformers script is: /data/jacquard

But if I call python prepare_data.py jacquard, I have the following error:
(orange) mkhan@pascal0:~/orange$ python prepare_data.py jacquard
/data/
Creating annotations for jacquard
Traceback (most recent call last):
  File "prepare_data.py", line 34, in <module>
    main(sys.argv[1:])
  File "prepare_data.py", line 28, in main
    TRANSFORMERS[dataset](Config(dataset=dataset), False).transform()
  File "/dstore/home/mkhan/orange/src/dataset_transformers/jacquard_transformer.py", line 27, in transform
    json.dump(self.handle_annotations(), fid)
  File "/dstore/home/mkhan/orange/src/dataset_transformers/jacquard_transformer.py", line 36, in handle_annotations
    assert any(txts)  # throw an error if dataset path is wrong
AssertionError

So seems that the algorithm is not able to find any of the txt files inside the specified folders.
What can be wrong?

Thank you!

**Comment by nickgkan** [comment]
Hi,

'/data/' is an absolute path which apparently doesn't exist. I think you meant to try 'data/' which is a relative path. If you want an absolute path, use this '/dstore/home/mkhan/orange/data/'.

Thanks

**Comment by mariiak2021** [comment]
Hi @nickgkan 

I have tried already all the possible options:
data, /data, data/, /data/, and /dstore/home/mkhan/orange/data/, /dstore/home/mkhan/orange/data
The result is always the same with the same error... :(

Thank you

**Comment by mariiak2021** [comment]
Hi @nickgkan 
I was able to solve the problem by modifying the code in jacquard_transformers.py and  jacquard_data_loader.py.
The problem was that this part of the path /Jacquard_Dataset_11/ was not included in the search.
