### ISSUE TITLE
About the pictures in the paper.

### ISSUE THREAD

**Issue by thk8181** [nickgkan/orange#5]
Hello, I am very honored and sorry to ask you again. I see that there are many visualization graphs in your paper, such as Fig. 2 and Fig. 3, those prediction graphs of network output and ground truth graphs, may I ask how they are generated?

**Comment by nickgkan** [comment]
Hi, thanks for still being interested in this work!

See [this issue](https://github.com/nickgkan/orange/issues/4) for a hint on how to run inference on new images.

I'm also attaching an old notebook I had used to visualize some results, but please keep in mind that it's quite messy and not officially released/supported.
[visuals.ipynb.zip](https://github.com/nickgkan/orange/files/8608085/visuals.ipynb.zip)
You need to modify cells 2 and 3 to your paths to the dataset and trained model. If you only want to visualize the annotations, consider commenting the parts that are not useful to you.

Best,
Nikos

**Comment by thk8181** [comment]
Received, thank you for your very valuable work and patient response.
